### ISSUE TITLE
Loop error

### ISSUE THREAD

**Issue by justwolfii** [DarkoPendragon/discord.js-musicbot-addon#111]
**Describe the bug**
If I will enable looping, then disable, than enable and disable again, bot will stop with error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/39670563/62876768-fc8c3f00-bd25-11e9-92ae-73663f952049.png)

**Versions**
- OS: Ubuntu 16.04
- Module version: 13.7.0
- Discord.js version: latest
- Node.js version: v8.15.0

**Additional context**
Error:
```
starting update
FINISHED UPDATE========
/home/justwolf/music/node_modules/opusscript/build/opusscript_native_wasm.js:8
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=function(status,toThrow){throw toThrow};Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"

TypeError: musicbot.queues.get(...).songs.slice is not a function
    at Music.musicbot.loopFunction (/home/justwolf/music/node_modules/discord.js-musicbot-addon/index.js:1240:60)
    at Client.client.on (/home/justwolf/music/node_modules/discord.js-musicbot-addon/index.js:409:38)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/home/justwolf/music/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/justwolf/music/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/justwolf/music/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/justwolf/music/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/justwolf/music/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
```

**Comment by justwolfii** [comment]
And next error while using remove and then queue command

```
Aug 12 16:16:37 Nikky node[32549]: Error: TypeError: queue.songs.push is not a function
Aug 12 16:16:37 Nikky node[32549]:     at Promise.then.catch (/home/justwolf/music/node_modules/discord.js-musicbot-addon/index.js:539:23)
Aug 12 16:16:37 Nikky node[32549]:     at <anonymous>
Aug 12 16:16:37 Nikky node[32549]:     at process._tickCallback (internal/process/next_tick.js:189:7)
Aug 12 16:17:02 Nikky node[32549]: /home/justwolf/music/node_modules/opusscript/build/opusscript_native_wasm.js:8
Aug 12 16:17:02 Nikky node[32549]: var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleAug 12 16:17:02 Nikky node[32549]: TypeError: musicbot.queues.get(...).songs.map is not a function
Aug 12 16:17:02 Nikky node[32549]:     at Music.musicbot.queueFunction (/home/justwolf/music/node_modules/discord.js-musicbot-addon/index.js:819:66)
Aug 12 16:17:02 Nikky node[32549]:     at Client.client.on (/home/justwolf/music/node_modules/discord.js-musicbot-addon/index.js:409:38)
Aug 12 16:17:02 Nikky node[32549]:     at emitOne (events.js:116:13)
Aug 12 16:17:02 Nikky node[32549]:     at Client.emit (events.js:211:7)
Aug 12 16:17:02 Nikky node[32549]:     at MessageCreateHandler.handle (/home/justwolf/music/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:Aug 12 16:17:02 Nikky node[32549]:     at WebSocketPacketManager.handle (/home/justwolf/music/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.jAug 12 16:17:02 Nikky node[32549]:     at WebSocketConnection.onPacket (/home/justwolf/music/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
Aug 12 16:17:02 Nikky node[32549]:     at WebSocketConnection.onMessage (/home/justwolf/music/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
Aug 12 16:17:02 Nikky node[32549]:     at WebSocket.onMessage (/home/justwolf/music/node_modules/ws/lib/event-target.js:120:16)
Aug 12 16:17:02 Nikky node[32549]:     at emitOne (events.js:116:13)
```

**Comment by DarkoPendragon** [comment]
Seems like something went wrong updating the positions of the songs and caused the songs object to be null. I'll look into it today.

**Comment by justwolfii** [comment]
Did you found it?

Btw.. I have another "problem". If I will use stop command, bot will leave channel, say that playback was finished and then he will join back, say playback finished again and leave again.
![image](https://user-images.githubusercontent.com/39670563/63068940-5ef76200-bf15-11e9-9aca-2bb5dcdc1bfd.png)

**Comment by DarkoPendragon** [comment]
Yeah, that's a general problem for the leave command I still haven't fixed. I've been working on and off on the project, but due to life issues just haven't had the time to update it.

Also I'm keeping this open so I don't forget about it.

**Comment by Uthsho** [comment]
same this errors im having...

**Comment by Dirky14** [comment]
Same error for me.
