### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SebyP4** [DarkoPendragon/discord.js-musicbot-addon#114]
C:\Users\sebip\OneDrive\Desktop\discord.js-musicbot-addon-master>node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'ytdl-core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\sebip\OneDrive\Desktop\discord.js-musicbot-addon-master\index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

C:\Users\sebip\OneDrive\Desktop\discord.js-musicbot-addon-master>PAUSE
Press any key to continue . . .

this is my error!

**Comment by jylescoad-ward** [comment]
You are installing addon as a bot, please do **NOT** do this.

This is an ***ADDON*** not a ***BOT***

There is a major diffrence.

**Comment by SebyP4** [comment]
@jylescoad-ward you can help me to put on my bot?sorry my english, i'm Romanian

**Comment by DarkoPendragon** [comment]
Simply [follow these examples](https://github.com/DarkoPendragon/discord.js-musicbot-addon/blob/master/examples/examples.md) and this won't happen.
