### ISSUE TITLE
Songs become a type that can't use the map method

### ISSUE THREAD

**Issue by Ambrosinae** [DarkoPendragon/discord.js-musicbot-addon#123]
**Describe the bug**
I've never used JS before but after consulting with canarado | サタン#0490 the title seems to describe the issue. It might also have something to do with the queue looping issue in the other issue that was posted here. The bot crashed upon me attempting to view the queue after the steps below to replicate it. The error is:

```
C:\Users\joshuaz\Desktop\discord_bot\node_modules\discord.js-musicbot-addon\index.js:846
          var newSongs = musicbot.queues.get(msg.guild.id).songs.map((video, index) => (`**${video.position + 1}:** __${video.title.replace(/\\/g, '\\\\').replace(/\`/g, '\\`').replace(/\*/g, '\\*').replace(/_/g, '\\_').replace(/~/g, '\\~').replace(/`/g, '\\`')}__`)).join('\n\n');
                                                                 ^

TypeError: musicbot.queues.get(...).songs.map is not a function
    at Music.musicbot.queueFunction (C:\Users\joshuaz\Desktop\discord_bot\node_modules\discord.js-musicbot-addon\index.js:846:66)
    at Client.client.on (C:\Users\joshuaz\Desktop\discord_bot\node_modules\discord.js-musicbot-addon\index.js:446:38)
    at Client.emit (events.js:198:13)
    at MessageCreateHandler.handle (C:\Users\joshuaz\Desktop\discord_bot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\joshuaz\Desktop\discord_bot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\joshuaz\Desktop\discord_bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\joshuaz\Desktop\discord_bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocketClient.internalOnMessage (C:\Users\joshuaz\Desktop\discord_bot\node_modules\@discordjs\uws\uws.js:103:5)
    at native.client.group.onMessage (C:\Users\joshuaz\Desktop\discord_bot\node_modules\@discordjs\uws\uws.js:57:12)
```

**To Reproduce**
To reproduce this bug:
I added three songs to the queue, skipped two songs, then checked the queue. The queue numbered two songs as "3". This may have been because I "searched" twice, but I didn't select a song after the first search and only selected a song after the second search, which ended up adding both songs to the queue. Then I attempted to view the queue and the bot crashed.

**Expected behavior**
The bot to not crash and the queue to list songs properly. Maybe there should be some way to cancel a prior search?

**Screenshots**
I added the stuff that would be in the screenshot to the code block above.

**Versions**
- Windows 10
- Module version: 13.8.1
- Discord.js version: 11.5.1
- Node.js version: 10.16.3

**Additional context**
N/A, I think?

**Comment by DarkoPendragon** [comment]
In 13.9+ searching will only allow one at a time per-person. I haven't been able to reproduce this anymore since adding it (update will be pushed sometime today).
