### ISSUE TITLE
Remove function issue

### ISSUE THREAD

**Issue by Happiness777** [DarkoPendragon/discord.js-musicbot-addon#140]
**Describe the bug**
To reproduce this bug: 
Something happens and the whole queue with such errors is removed:

2020-02-28T18:29:38.212219+00:00 app[worker.1]: Error: TypeError: queue.songs.push is not a function
2020-02-28T18:29:38.212242+00:00 app[worker.1]:     at /app/node_modules/discord.js-musicbot-addon/index.js:596:23
2020-02-28T18:29:38.212243+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2020-02-28T18:29:38.212243+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-02-28T18:30:04.592394+00:00 app[worker.1]: /app/node_modules/discord.js-musicbot-addon/index.js:1303
2020-02-28T18:30:04.592445+00:00 app[worker.1]:       let test = musicbot.queues.get(msg.guild.id).songs.find(x => x.position == parseInt(suffix) - 1);
2020-02-28T18:30:04.592448+00:00 app[worker.1]:                                                          ^
2020-02-28T18:30:04.592448+00:00 app[worker.1]: 
2020-02-28T18:30:04.592449+00:00 app[worker.1]: TypeError: musicbot.queues.get(...).songs.find is not a function
2020-02-28T18:30:04.592450+00:00 app[worker.1]:     at Music.musicbot.removeFunction (/app/node_modules/discord.js-musicbot-addon/index.js:1303:58)
2020-02-28T18:30:04.592451+00:00 app[worker.1]:     at Client.<anonymous> (/app/node_modules/discord.js-musicbot-addon/index.js:461:38)
2020-02-28T18:30:04.592452+00:00 app[worker.1]:     at Client.emit (events.js:311:20)
2020-02-28T18:30:04.592453+00:00 app[worker.1]:     at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
2020-02-28T18:30:04.592454+00:00 app[worker.1]:     at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
2020-02-28T18:30:04.592454+00:00 app[worker.1]:     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
2020-02-28T18:30:04.592455+00:00 app[worker.1]:     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
2020-02-28T18:30:04.592455+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/discord.js/node_modules/ws/lib/event-target.js:120:16)
2020-02-28T18:30:04.592456+00:00 app[worker.1]:     at WebSocket.emit (events.js:311:20)
2020-02-28T18:30:04.592456+00:00 app[worker.1]:     at Receiver.receiverOnMessage (/app/node_modules/discord.js/node_modules/ws/lib/websocket.js:789:20)

**To Reproduce**
Type (prefix)remove (position)

**Expected behavior**
Delete music at a certain position

**Versions**
- Deployed on Heroku
- Module version 13.9.1
- Node.js version 12.16.1

**Additional context**
This problem is most likely in the "remove" function

**Comment by NightcoreRYT** [comment]
I've been having the same issue.
