### ISSUE TITLE
Bot crash when trying to play

### ISSUE THREAD

**Issue by 112madgamer** [DarkoPendragon/discord.js-musicbot-addon#21]
When trying to play a song the bot crashes 

Error:
```
/home/doom/Desktop/Ghost-nodejs/node_modules/fluent-ffmpeg/lib/utils.js:433
          return lines.join('\n');
                       ^

RangeError: Maximum call stack size exceeded
    at Array.join (native)
    at Object.get (/home/doom/Desktop/Ghost-nodejs/node_modules/fluent-ffmpeg/lib/utils.js:433:24)
    at DestroyableTransform.<anonymous> (/home/doom/Desktop/Ghost-nodejs/node_modules/fluent-ffmpeg/lib/processor.js:500:48)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)

```
And sometimes this: 
```internal/errors.js:103
function message(key, args) {
                ^

RangeError: Maximum call stack size exceeded
    at message (internal/errors.js:103:17)
    at new NodeError (internal/errors.js:25:13)
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:573:10)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)
    at DestroyableTransform.emit (events.js:165:20)```

ffmpeg version: ``` ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-shared --enable-version3 --enable-omx
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile} ```

**Comment by DarkoPendragon** [comment]
This (should) have been resolved in a prior update, I just forgot to mark it off. It's a problem with audio-stream, since it's severely outdated. It's on my fault for not removing it and reworking for just ytdl. If it occurs again, feel free to re-open this.
