### ISSUE TITLE
Leave not work

### ISSUE THREAD

**Issue by IxJesus** [DarkoPendragon/discord.js-musicbot-addon#51]
the leave command does not work when the music ends

**Comment by BluSpring** [comment]
Any errors? I'll try helping.

**Comment by IxJesus** [comment]
The error is that when it finishes playing the music I put the leave command, it does not execute it (the bot does not leave the voice channel)

**Comment by SirNightmare** [comment]
U can only use the Leave command while a song is playing that's why it wont leave.

**Comment by RazorApple** [comment]
"No work plz fix" isnt a great way to describe a issue.
The error is below


2018-10-20T18:53:29.646790+00:00 app[worker.1]: /app/node_modules/discord.js-musicbot-addon/index.js:1891
2018-10-20T18:53:29.646843+00:00 app[worker.1]: if (!vc.player.dispatcher) return;
2018-10-20T18:53:29.646845+00:00 app[worker.1]: ^
2018-10-20T18:53:29.646847+00:00 app[worker.1]:
2018-10-20T18:53:29.646849+00:00 app[worker.1]: TypeError: Cannot read property 'player' of null
2018-10-20T18:53:29.646857+00:00 app[worker.1]: at Timeout.setTimeout [as _onTimeout] (/app/node_modules/discord.js-musicbot-addon/index.js:1891:17)
2018-10-20T18:53:29.646859+00:00 app[worker.1]: at ontimeout (timers.js:498:11)
2018-10-20T18:53:29.646860+00:00 app[worker.1]: at tryOnTimeout (timers.js:323:5)
2018-10-20T18:53:29.646862+00:00 app[worker.1]: at Timer.listOnTimeout (timers.js:290:5)
2018-10-20T18:53:29.740391+00:00 heroku[worker.1]: State changed from up to crashed
2018-10-20T18:53:29.742684+00:00 heroku[worker.1]: State changed from crashed to starting
2018-10-20T18:53:29.724334+00:00 heroku[worker.1]: Process exited with status 1

**Comment by RazorApple** [comment]
to workaround this issue
you can make a mleave command.
