### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by XSRed** [DarkoPendragon/discord.js-musicbot-addon#56]
Whenever I typed the `play` command followed by a song name or URL,
I get this error:

    Error: Dispatcher SetLast: no server queue
        at musicbot.setLast.then.catch (C:\Discord\node_modules\discord.js-musicbot-addon\index.js:2141:36)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

    TypeError: Cannot read property 'url' of undefined
        at Promise.then.connection (C:\Discord\node_modules\discord.js-musicbot-addon\index.js:2150:61)
        at <anonymous>

    Error: Dispatcher SetLast: no server queue
        at musicbot.setLast.then.catch (C:\Discord\node_modules\discord.js-musicbot-addon\index.js:2141:36)
        at <anonymous>

Screenshot: http://prntscr.com/koi4g0

**Comment by oli877877877** [comment]
The module is broken at the moment. Darko should fix it at sometime he just took a little break. Join the support server for updates: https://discordapp.com/invite/FKYrX4X
