### ISSUE TITLE
client.on is not a function

### ISSUE THREAD

**Issue by MrBoombastic** [DarkoPendragon/discord.js-musicbot-addon#63]
Trying to run this code:

```javascript
const Discord = require('discord.js');
class Bot extends Discord.Client {
  constructor(options) {
    super(options);
    this.music = require("discord.js-musicbot-addon");
  }
}
const client = new Bot();
client.music.start({
  youtubeKey: "token"
});
client.login("token");
```
But I have got an error:

```C:\Users\Antoni\Desktop\testmuza>node bot.js
C:\Users\Antoni\node_modules\discord.js-musicbot-addon\index.js:284
  client.on("ready", (client) => {
         ^

TypeError: client.on is not a function
    at Object.exports.start (C:\Users\Antoni\node_modules\discord.js-musicbot-addon\index.js:284:10)
    at Object.<anonymous> (C:\Users\Antoni\Desktop\testmuza\bot.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

C:\Users\Antoni\Desktop\testmuza>
```

 FFMPEG, Opusscript, Discord.js installed. Node - 10.9.0. NPM - 6.2.0.

**Comment by DarkoPendragon** [comment]
You're not passing the client to the module.
```js
client.music.start(client, { options });
```
